blank_issues_enabled: false
contact_links:
 - name: Getting Help on libp2p
   url: https://libp2p.io/help
   about: All information about how and where to get help on libp2p.
 - name: libp2p Official Forum
   url: https://discuss.libp2p.io
   about: Please post general questions, support requests, and discussions here.
